import { v } from "convex/values";
import { internal } from "./_generated/api";
import type { Doc, Id } from "./_generated/dataModel";
import { internalAction, internalMutation, internalQuery } from "./_generated/server";
import { deleteClerkUser, fetchClerkUser, getClerkUserId } from "./lib/clerk";
import { getClerkProfile, getMissingProfilePatch, hasProfilePatch } from "./lib/userProfiles";
import { requireAdmin } from "./lib/auth";

const BACKFILL_BATCH_SIZE = 50;

export const getUsersForBackfill = internalQuery({ args: { cursor: v.union(v.string(), v.null()) }, handler: async (ctx, args) => { await requireAdmin(ctx); return await ctx.db.query("users").order("asc").paginate({ cursor: args.cursor, numItems: BACKFILL_BATCH_SIZE }); } });
export const patchMissingUserProfileFields = internalMutation({ args: { userId: v.id("users"), clerkId: v.string(), email: v.string(), firstName: v.string(), lastName: v.string() }, handler: async (ctx, args) => { const user = await ctx.db.get("users", args.userId); if (!user) return false; const patch = getMissingProfilePatch(user, args); const needsClerkIdMigration = user.clerkId !== args.clerkId; if (!hasProfilePatch(patch) && !needsClerkIdMigration) return false; await ctx.db.patch("users", user._id, { ...patch, clerkId: args.clerkId, updatedAt: Date.now() }); return true; } });
export const getUserForProfileSync = internalQuery({ args: { userId: v.id("users") }, handler: async (ctx, args) => { const user = await ctx.db.get("users", args.userId); return user ? { clerkUserId: getClerkUserId(user.clerkId) } : null; } });
export const syncUserProfileFromClerk = internalAction({ args: { userId: v.id("users") }, handler: async (ctx, args) => { const user = await ctx.runQuery(internal.userMaintenance.getUserForProfileSync, { userId: args.userId }); if (!user) return null; const clerkSecretKey = process.env.CLERK_SECRET_KEY; if (!clerkSecretKey) throw new Error("User profile sync is not configured: CLERK_SECRET_KEY is missing from the Convex environment"); const clerkUser = await fetchClerkUser(user.clerkUserId, clerkSecretKey); await ctx.runMutation(internal.userMaintenance.patchMissingUserProfileFields, { userId: args.userId, clerkId: clerkUser.id, ...getClerkProfile(clerkUser) }); return null; } });
export const getUserForDeletion = internalQuery({ args: { userId: v.id("users") }, handler: async (ctx, args) => { await requireAdmin(ctx); const user = await ctx.db.get("users", args.userId); if (!user) throw new Error("User not found"); return { clerkUserId: getClerkUserId(user.clerkId) }; } });
export const deleteUserRow = internalMutation({ args: { userId: v.id("users") }, handler: async (ctx, args) => { const user = await ctx.db.get("users", args.userId); if (user) await ctx.db.delete("users", args.userId); return null; } });
export const removeUser = internalAction({ args: { userId: v.id("users") }, handler: async (ctx, args) => { const { clerkUserId } = await ctx.runQuery(internal.userMaintenance.getUserForDeletion, { userId: args.userId }); const clerkSecretKey = process.env.CLERK_SECRET_KEY; if (!clerkSecretKey) throw new Error("User deletion is not configured: CLERK_SECRET_KEY is missing from the Convex environment"); await deleteClerkUser(clerkUserId, clerkSecretKey); try { await ctx.runMutation(internal.userMaintenance.deleteUserRow, { userId: args.userId }); } catch (error) { throw new Error(`Clerk user ${clerkUserId} was deleted, but the Convex user row could not be removed. Retry this action to finish cleanup. ${error instanceof Error ? error.message : "Unknown Convex error"}`); } return null; } });
export const backfillMissingUserProfiles = internalAction({ args: { cursor: v.union(v.string(), v.null()) }, handler: async (ctx, args): Promise<{ failedUserIds: Id<"users">[]; isDone: boolean; nextCursor: string | null; scannedCount: number; updatedCount: number }> => { const result: { continueCursor: string; isDone: boolean; page: Doc<"users">[] } = await ctx.runQuery(internal.userMaintenance.getUsersForBackfill, { cursor: args.cursor }); const clerkSecretKey = process.env.CLERK_SECRET_KEY; if (!clerkSecretKey) throw new Error("User backfill is not configured: CLERK_SECRET_KEY is missing from the Convex environment"); const failedUserIds: Id<"users">[] = []; let updatedCount = 0; for (const user of result.page) { try { const clerkUser = await fetchClerkUser(getClerkUserId(user.clerkId), clerkSecretKey); const didUpdate: boolean = await ctx.runMutation(internal.userMaintenance.patchMissingUserProfileFields, { userId: user._id, clerkId: clerkUser.id, ...getClerkProfile(clerkUser) }); if (didUpdate) updatedCount += 1; } catch { failedUserIds.push(user._id); } } return { failedUserIds, isDone: result.isDone, nextCursor: result.isDone ? null : result.continueCursor, scannedCount: result.page.length, updatedCount }; } });
